CREATE TABLE `slack_comments` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `parent_message_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '원본 메시지 ID',
  `comment_message_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '댓글 메시지 ID',
  `user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '댓글 작성자 ID',
  `user_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '댓글 작성자 이름',
  `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '댓글 내용',
  `comment_timestamp` datetime NOT NULL COMMENT '댓글 작성 시간',
  `is_edited` tinyint(1) DEFAULT '0' COMMENT '댓글 수정 여부',
  `edit_count` int DEFAULT '0' COMMENT '수정 횟수',
  `previous_content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '이전 댓글 내용',
  `message_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'unknown' COMMENT '원본 메시지 유형 (exchange_rate, work_journal)',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '데이터베이스 저장 시간',
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '마지막 업데이트 시간',
  PRIMARY KEY (`id`),
  KEY `slack_comments_parent_message_IDX` (`parent_message_id`),
  KEY `slack_comments_comment_message_IDX` (`comment_message_id`),
  KEY `slack_comments_user_IDX` (`user_id`),
  KEY `slack_comments_timestamp_IDX` (`comment_timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;